### ISSUE TITLE
[Bug] Customizable Webhook user

### ISSUE THREAD

**Issue by Silence02ru** [xIRoXaSx/TwitchNotifier#9]
**Which version do you use?**
- Release Version: 2.1.1
- OS: Debian 11
- Console Errors: -

**Screenshots**
![DiscordPTB_hBs6bPKEON](https://user-images.githubusercontent.com/61424512/206912179-c33b617c-8a1a-4d26-bd11-0b0c0ec823ba.png)

**Additional context**
The information of the webhook is not updated, it always indicates the same user

**Comment by xIRoXaSx** [comment]
I've spotted the issue.  
Will try to get it fixed asap but a current workaround for you might be to separate the channels into their own `OnLiveEvent` node with just one channel.

**Comment by xIRoXaSx** [comment]
This issue has been fixed (e01fcc8f58cf8562a41b4deccfbdca66b05e7fda).  
Please use the latest release.
